### PR TITLE
Wjlove update - Support for the ScioSense ENS160 Sensor

### PR DESCRIPTION
**Pull request by wjlove**
I've included code that supports the ScioSense ens160 sensor and tested it against both the ScioSense development kit and the DFRobot Gravity sensor module.

### CODE REVIEW

**Comment by alanb128** [comment]
Just a couple items:
1. In testing I was getting "module not found" errors from the new `DFRobot_ENS160.py` file that requires smbus and spidev. I think those need to be added to the `pip3 install` line in the IAQ Dockerfile and then it works fine.
2. My ENS160 came with the address switch set to 0x53 and it did not work unless I changed the address to 0x52. Should we support either address?

**Comment by wjlove** [comment]
For item 1) yes, my mistake I forgot to include the correct Dockerfile.template when I copied over the files related to the ens160 update. 

For item 2) We can support either address or document (like we do with changing the led matrix address) how to set the correct address.  Given a quick scan of the list at https://i2cdevices.org/addresses there is overlap of environmental sensor devices at both addresses so I think picking one and documenting the setting is the better way to go.  Thoughts?

**Comment by alanb128** [comment]
For item 2) so far the ENS160 addresses do not conflict with any I2C devices (sensors/displays) the IAQ supports, so I think we could check for either one. If not, I would go with whatever the default setting is. Since the ENS160 uses a physical switch, I'm not sure if there is a default? (i.e. does it always come from the factory on the same address setting?)

**Comment by alanb128** [comment]
I also noticed that the logging code in the new `DFRobot_ENS160.py` is affecting the logging display/formatting in `iaq.py` so I'll see if there is an easy workaround.

**Comment by wjlove** [comment]
Again for item 2) in general I think it is a bad idea to have a single device using two address when only one is necessary, especially in an address space that is limited and where we have known possible future conflicts.  All three of my devices came preset to 0x53 and it was the code that I copied that was configured to look for 0x52.  At the time I didn't think much about which one to change so I just flipped the device switch.   Upon reflection I think it is a better idea to change the code and document the existence of the switch and have the user verify that it is set correctly.

**Comment by wjlove** [comment]
In regards to the logging stuff, I think this is something fundamental I don't really understand about python yet.   I thought that other than things made specifically available to general use (like class declarations) everything was internal to the module.    If this is not the case then yes there could be all sorts of problems with that module as it does modify the logging functions.

A quick (slightly less educated) scan of the file appears to reveal that most of that logging code is redundant and could be commented out.  I will do a deeper scan and some testing today.

**Comment by wjlove** [comment]
As quick test I removed all the logging setup except for `logger = logging.getLogger()` and that appears to return to the correct format and the logging level.  When I removed the previous line as well things broke and the ens160 was never found, I don't understand why.

**Comment by alanb128** [comment]
Sure, makes sense to pick one address for the ENS160, so the default 0x53 ?

**Comment by wjlove** [comment]
Yes.  Just finished testing with 0x53 as the default.

**Pull request closed without merging**
